name = input("Enter your name: ")
age = int(input("Enter your age: "))
city = input("Enter your city: ")
course = input("Enter your course: ")
goal = input("Enter your career goal: ")

print("\n--- My Bio Card ---")
print(f"Name: {name}")
print(f"Age: {age}")
print(f"City: {city}")
print(f"Course: {course}")
print(f"Career Goal: {goal}")